spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${username}
    password: ${passwd}
    url: ${mysql_url}
  jpa:
    show-sql: true
    database: MYSQL
server:
  context-path: /
  port: 8080


