spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/ssm_crud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database: MYSQL
server:
  context-path: /cms
  port: 8099


